const accountId = 144533
let accountEmail ="yashraj102723@gmail.com"
var accountPassword = "12345"
accountCity = "Jaipur"
let accountState;
// accountId = 2 //not allowed

accountEmail = "xyz@hc.com"
accountPassword = "21212121"
accountCity = "mathura"
console.log(accountId);

/*
prefer not to use var
bczz of issue in block scope and
functional scope

*/

console.table([accountId ,accountEmail ,accountPassword , accountCity ,accountState])
